services:
  - type: web
    runtime: node
    name: wellness-backend
    rootDir: backend-auth
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: PORT
        value: 10000

  - type: web
    runtime: static
    name: wellness-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
